#! /bin/sh

umask 077

pkv_home="$HOME/.pkv"
gnupg_cmd="$(which gpg) --homedir $pkv_home/gpg"
dmenu_cmd="$(which dmenu) -i -l 10 -nb #440000"

# Generates a new hmac_key. Take care to extract the mapping of the previous key
# beforehand
gen_new_hmac_key () {
	dd bs=64 count=1 if=/dev/random 2>/dev/null |
		base64 -w 0 |
		$gnupg_cmd -e -a >"$pkv_home/hmac_key.gpg"
}

get_value () {
	local hmackey="$(</dev/null $gnupg_cmd -d "$pkv_home/hmac_key.gpg")"

	local key
	key="$(</dev/null $gnupg_cmd -d "$pkv_home/keylist" |
		$dmenu_cmd -p "Select Key:")"
	if [ "$?" = "1" ]; then
		exit 1;
	fi

	local fname="$(echo "$key" |
		openssl sha512 -hex -hmac "$hmackey" |
		cut -d' ' -f2)"

	local val="$(</dev/null 2>/dev/null $gnupg_cmd -d "$pkv_home/keys/$fname")"
	local uname="${val%% *}"
	local passw="${val#* }"
	echo -n "$uname" | xclip
	sleep 3s
	echo -n "$passw" | xclip
	sleep 3s
	echo -n "" | xclip
}

edit_value () {
	local hmackey="$(</dev/null $gnupg_cmd -d "$pkv_home/hmac_key.gpg")"
	local keylist="$(</dev/null $gnupg_cmd -d "$pkv_home/keylist")"

	local key
	key="$(echo -n "$keylist" |
		$dmenu_cmd -p "Select Key:")"
	if [ "$?" = "1" ]; then
		exit 1
	fi

	local fname="$(echo "$key" |
		openssl sha512 -hex -hmac "$hmackey" |
		cut -d' ' -f2)"
	local oldval="$(</dev/null 2>/dev/null $gnupg_cmd -d "$pkv_home/keys/$fname")"

	local newval
	newval="$(echo "$oldval" |
		$dmenu_cmd -p "New Value:")"
	if [ "$?" = "1" ]; then
		exit 1
	fi

	if [ -z "$newval" ]; then
		&>/dev/null rm "$pkv_home/keys/$fname"

		# remove key from keylist
		echo -n "$keylist" |
			sort -u |
			grep -v -F -x -e "$key" |
			$gnupg_cmd 2>/dev/null -e -a >"$pkv_home/keylist"
	else
		echo "$newval" |
			$gnupg_cmd 2>/dev/null -e -a >"$pkv_home/keys/$fname"

		# insert new key to /keylist
		echo -e -n "$key\n$keylist" |
			sort -u |
			$gnupg_cmd 2>/dev/null -e -a >"$pkv_home/keylist"
	fi
}

# add the key to gpg-agent's cache to avoid issues in the following pipelines
# this unfortunately is racy, because the cache could be invalidated right after
# the following command. $gnupg_cmd should only be called once per pipeline.
</dev/null &>/dev/null $gnupg_cmd -d "$pkv_home/keylist"

case $1 in
	"get")
		get_value
		;;
	"edit")
		edit_value
		;;
	*)
		echo fail
		exit 1
		;;
esac

#gen_new_hmac_key
#edit_value
